name: Main Workflow

on : push

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Pulling code
        uses: actions/checkout@v3

      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pushing to dockerhub
        run: |
          docker build -t mshallom/simple-node .
          docker push mshallom/simple-node:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pushing to github container registry
        run: |
          docker build . --tag ghcr.io/micah-shallom/simple-node:latest
          docker push ghcr.io/micah-shallom/simple-node:latest

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ECR_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: pushing into ECR
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/simple-node:latest .
          docker push ${{ secrets.ECR_REGISTRY }}/simple-node:latest

